meta: config/boards/hellen_meta.h

pins:
  - pin: 1B
    id: TLE9104_0_OUT_3
    class: outputs
    ts_name: ___ Port injector 4
    function: Port injector 4
    color: orange/brown
    type: ls

  - pin: 2B
    id: TLE9104_0_OUT_2
    class: outputs
    ts_name: ___ Port injector 3
    function: Port injector 3
    color: blue
    type: ls

  - pin: 3B
    id: TLE9104_0_OUT_1
    class: outputs
    ts_name: ___ Port injector 2
    function: Port injector 2
    color: white
    type: ls

  - pin: 4B
    id: TLE9104_0_OUT_0
    class: outputs
    ts_name: ___ Port injector 1
    function: Port injector 1
    color: green
    type: ls

  - pin: 5B
    id: TLE9104_1_OUT_0
    class: outputs
    ts_name: ___ Main Relay Control
    function: Main relay control
    type: ls
    color: grey

  - pin: 6B
    meta: H144_IN_VBATT
    class: analog_inputs
    function: ECU power supply / Ignition Key Power
    ts_name: ___ Battery Sense
    type: 12v

  - pin: 7B
    id: TLE9104_1_OUT_1
    class: outputs
    function: Fuel Pump Relay Output
    type: ls
    ts_name: ___ Fuel Pump

  - pin: 8B
    id: TLE9104_1_OUT_2
    class: outputs
    function: Fan 1
    type: ls
    ts_name: ___ Fan 1

  - pin: 9B
    id: TLE9104_1_OUT_3
    class: outputs
    function: Fan 2
    color: yellow
    type: ls
    ts_name: ___ Fan 2

  - pin: 10B
    meta: H144_IN_CRANK
    class: event_inputs
    function: Crank / VR 9924 Negative
    ts_name: ___ VR Negative

  - pin: 11B
    function: Crank / VR 9924 Positive

  - pin: 16B
    function: Knock Input

  - pin: 19B
    function: PPS 1
    type: av
    meta: H144_IN_PPS
    class: analog_inputs
    ts_name: ___ PPS1
    color: white

  - pin: 20B
    function: PPS 2
    type: av
    meta: H144_IN_PPS2
    class: analog_inputs
    ts_name: ___ PPS2
    color: orange/brown

  - pin: 21B
    id: [H144_IN_SENS1, H144_IN_SENS1]
    class: [event_inputs, switch_inputs]
    function: Digital Input 1
    ts_name: ___ Digital Input 1
    color: white

  - pin: 22B
    id: [H144_IN_AUX2_DIGITAL, H144_IN_AUX2_DIGITAL, H144_IN_AUX2]
    class: [event_inputs, switch_inputs, analog_inputs]
    function: Input 2 Digital / Analog / SENT
    ts_name: ___ Input 2
    color: yellow

  - pin: 23B
    function: Fuel Low Pressure
    type: av
    meta: H144_IN_AUX4
    class: analog_inputs
    ts_name: ___ Fuel Low Pressure

  - pin: 24B
    function: Fuel High Pressure
    type: av
    meta: H144_IN_MAP3
    class: analog_inputs
    ts_name: ___ Fuel High Pressure

  - pin: 26B
    function: Power GND
    type: gnd

  - pin: 27B
    id: [H144_IN_SENS2, H144_IN_SENS2]
    class: [event_inputs, switch_inputs]
    function: Digital Input 3
    ts_name: ___ Digital Input 3
    color: yellow

  - pin: 28B
    id: [H144_IN_SENS3, H144_IN_SENS3]
    class: [event_inputs, switch_inputs]
    function: Digital Input 4
    ts_name: ___ Digital Input 4

  - pin: 29B
    id: TLE9104_2_OUT_0
    class: outputs
    ts_name: ___ VVT1
    function: VVT1
    type: ls
    color: orange

  - pin: 30B
    id: TLE9104_2_OUT_1
    class: outputs
    ts_name: ___ VVT2
    function: VVT2
    type: ls
    color: blue

  - pin: 31B
    id: TLE9104_2_OUT_2
    class: outputs
    ts_name: ___ VVT3
    function: VVT3
    type: ls
    color: white

  - pin: 32B
    id: TLE9104_2_OUT_3
    class: outputs
    ts_name: ___ VVT4
    function: VVT4
    type: ls
    color: green


info:
  title: AlphaX 4K-GDI
  name: AlphaX 4K-GDI
  order: 1
  board_url: https://rusefi.com/s/4K-GDI
  image:
    file: 34pins-3k-B.jpg
  pins:
    - pin: 1B
      x: 95
      y: 90
    - pin: 2B
      x: 120
      y: 90
    - pin: 3B
      x: 155
      y: 90
    - pin: 4B
      x: 180
      y: 90
    - pin: 5B
      x: 205
      y: 90
    - pin: 6B
      x: 230
      y: 90
    - pin: 7B
      x: 255
      y: 90
    - pin: 8B
      x: 280
      y: 90
    - pin: 9B
      x: 305
      y: 90
    - pin: 10B
      x: 110
      y: 120
    - pin: 11B
      x: 135
      y: 120
    - pin: 12B
      x: 160
      y: 120
    - pin: 13B
      x: 185
      y: 120
    - pin: 14B
      x: 210
      y: 120
    - pin: 15B
      x: 235
      y: 120
    - pin: 16B
      x: 260
      y: 120
    - pin: 17B
      x: 285
      y: 120
    - pin: 18B
      x: 110
      y: 150
    - pin: 19B
      x: 135
      y: 150
    - pin: 20B
      x: 160
      y: 150
    - pin: 21B
      x: 185
      y: 150
    - pin: 22B
      x: 210
      y: 150
    - pin: 23B
      x: 235
      y: 150
    - pin: 24B
      x: 260
      y: 150
    - pin: 25B
      x: 285
      y: 150
    - pin: 26B
      x: 95
      y: 180
    - pin: 27B
      x: 120
      y: 180
    - pin: 28B
      x: 155
      y: 180
    - pin: 29B
      x: 180
      y: 180
    - pin: 30B
      x: 205
      y: 180
    - pin: 31B
      x: 230
      y: 180
    - pin: 32B
      x: 255
      y: 180
    - pin: 33B
      x: 280
      y: 180
    - pin: 34B
      x: 305
      y: 180
