name: Build microRusEFI Firmware

on:

  workflow_dispatch:

jobs:
  build-microrusefi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install mtools
        run: sudo apt-get install mtools

      - name: Install mingw-w64
        run: sudo apt-get install mingw-w64
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Build Environment Variables
        run: |
          echo "BOARD_META_PATH=config/boards/microrusefi/meta-info-mre_f4.env" >> $GITHUB_ENV
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.3.Rel1'

      - name: Test Arm GCC Compiler
        run: arm-none-eabi-gcc -v

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

   #   - name: Clean Previous Builds
   #     working-directory: ./firmware
   #     run: |
   #       make clean

      - name: Build Firmware for mre-legacy_f4
        working-directory: ./firmware
        run: |
          bash bin/compile.sh $BOARD_META_PATH bundles --output-sync=recurse
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mre-legacy_f4-firmware
          path: |
            ./firmware/deliver/rusefi*.bin
            ./firmware/deliver/rusefi*.hex
            ./firmware/deliver/rusefi*.dfu
            ./firmware/deliver/rusefi*.ini
            
            ./firmware/tunerstudio/generated/rusefi_mre_f4*.ini
      #      ./firmware/rusefi.snapshot.mre_f4/rusefi_mre_f4*.ini
      #      ./firmware/rusefi.snapshot.mre_f4/
